---
# ==============================================================================
# CREATE EC2 KEY PAIR AND SAVE PRIVATE KEY LOCALLY
# ==============================================================================

- name: Create and Download EC2 Key
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - amazon.aws

  vars:
    key_name: my_keypair
    aws_region: us-east-2
    key_path: ./sample-key.pem

  tasks:

    # --------------------------------------------------------------------------
    # TASK 1: Ensure old key does not exist (Safe Re-run)
    # --------------------------------------------------------------------------
    - name: Delete existing key if present
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: absent
      ignore_errors: yes

    # --------------------------------------------------------------------------
    # TASK 2: Create EC2 Key Pair
    # --------------------------------------------------------------------------
    - name: Create EC2 key pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: present
      register: keyout

    # --------------------------------------------------------------------------
    # TASK 3: Display Output
    # --------------------------------------------------------------------------
    - name: Show key output
      debug:
        var: keyout

    # --------------------------------------------------------------------------
    # TASK 4: Save Private Key Locally
    # --------------------------------------------------------------------------
    - name: Save private key locally
      copy:
        content: "{{ keyout.key.private_key }}"
        dest: "{{ key_path }}"
        mode: '0600'