---
- name: Setup Vprofile Compute Layer
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - amazon.aws

  tasks:

    # ================= IMPORT VARIABLES =================

    - name: Import Bastion Variables
      include_vars: vars/bastion_setup.yml

    - name: Import VPC Output Variables
      include_vars: vars/output_vars.yml

    # ================= CREATE KEY =================

    - name: Create EC2 Key for Bastion
      amazon.aws.ec2_key:
        name: "{{ keyName }}"
        region: "{{ region }}"
        state: present
      register: key_out

    - name: Save private key
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: '0600'
      when: key_out.changed

    # ================= BASTION SECURITY GROUP =================

    - name: Create Security Group for Bastion
      amazon.aws.ec2_security_group:
        name: Bastion-host-sg
        description: Allow SSH from My IP
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    # ================= APP SECURITY GROUP =================

    - name: Create Security Group for App Tier
      amazon.aws.ec2_security_group:
        name: App-tier-sg
        description: Allow SSH from Bastion and HTTP from ALB
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            group_name: Bastion-host-sg
      register: AppSG_out

    # ================= DB SECURITY GROUP =================

    - name: Create Security Group for DB Tier
      amazon.aws.ec2_security_group:
        name: DB-tier-sg
        description: Allow MySQL from App Tier SG
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_name: App-tier-sg
      register: DBSG_out

    # ================= BASTION HOST =================

    - name: Ensure Bastion Host
      amazon.aws.ec2_instance:
        name: Bastion_host
        key_name: "{{ keyName }}"
        region: "{{ region }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        vpc_subnet_id: "{{ pubsub3id }}"
        security_group: Bastion-host-sg
        network:
          assign_public_ip: true
        state: running
        exact_count: 1
        filters:
          "tag:Name": Bastion_host
          "instance-state-name": ["pending","running","stopping","stopped"]
        wait: yes
        tags:
          Name: Bastion_host
          Tier: Bastion
          Project: Vprofile
          Owner: DevOpsTeam
      register: bastionHost_out

    # ================= PRIVATE APP INSTANCE 1 =================

    - name: Ensure Private App Instance 1
      amazon.aws.ec2_instance:
        name: AppInstance1
        key_name: "{{ keyName }}"
        region: "{{ region }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        vpc_subnet_id: "{{ privsub1id }}"
        security_group: App-tier-sg
        network:
          assign_public_ip: false
        state: running
        exact_count: 1
        filters:
          "tag:Name": AppInstance1
          "instance-state-name": ["pending","running","stopping","stopped"]
        wait: yes
        tags:
          Name: AppInstance1
          Tier: App
          Project: Vprofile
          Owner: DevOpsTeam
      register: app1_out

    # ================= PRIVATE APP INSTANCE 2 =================

    - name: Ensure Private App Instance 2
      amazon.aws.ec2_instance:
        name: AppInstance2
        key_name: "{{ keyName }}"
        region: "{{ region }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        vpc_subnet_id: "{{ privsub3id }}"
        security_group: App-tier-sg
        network:
          assign_public_ip: false
        state: running
        exact_count: 1
        filters:
          "tag:Name": AppInstance2
          "instance-state-name": ["pending","running","stopping","stopped"]
        wait: yes
        tags:
          Name: AppInstance2
          Tier: App
          Project: Vprofile
          Owner: DevOpsTeam
      register: app2_out