---
- name: Setup Vprofile Compute Layer
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - amazon.aws

  tasks:

    # ================= IMPORT VARIABLES =================

    - name: Import Bastion Variables
      include_vars: vars/bastion_setup.yml

    - name: Import VPC Output Variables
      include_vars: vars/output_vars.yml

    # ================= CREATE KEY =================

    - name: Create EC2 Key for Bastion
      amazon.aws.ec2_key:
        name: "{{ keyName }}"
        region: "{{ region }}"
        state: present
      register: key_out

    - name: Save private key
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: '0600'
      when: key_out.changed

    # ================= BASTION SECURITY GROUP =================

    - name: Create Security Group for Bastion
      amazon.aws.ec2_security_group:
        name: Bastion-host-sg
        description: Allow SSH from My IP
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    # ================= APP SECURITY GROUP =================

    - name: Create Security Group for App Tier
      amazon.aws.ec2_security_group:
        name: App-tier-sg
        description: Allow SSH from Bastion and HTTP from ALB
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          # SSH from Bastion SG
          - proto: tcp
            from_port: 22
            to_port: 22
            group_name: Bastion-host-sg
      register: AppSG_out

    # ================= DB SECURITY GROUP =================

    - name: Create Security Group for DB Tier
      amazon.aws.ec2_security_group:
        name: DB-tier-sg
        description: Allow MySQL from App Tier SG
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_name: App-tier-sg
      register: DBSG_out

    # ================= BASTION HOST =================

    - name: Create Bastion Host
      amazon.aws.ec2_instance:
        name: Bastion_host
        key_name: "{{ keyName }}"
        region: "{{ region }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        vpc_subnet_id: "{{ pubsub3id }}"
        security_group: Bastion-host-sg
        network:
          assign_public_ip: true
        wait: yes
        tags:
          Project: Vprofile
          Owner: DevOpsTeam
      register: bastionHost_out

    # ================= PRIVATE APP INSTANCE 1 =================

    - name: Create Private App Instance in privsub1
      amazon.aws.ec2_instance:
        name: AppInstance
        key_name: "{{ keyName }}"
        region: "{{ region }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        vpc_subnet_id: "{{ privsub1id }}"
        security_group: App-tier-sg
        network:
          assign_public_ip: false
        wait: yes
        tags:
          Tier: App
          Project: Vprofile
          Owner: DevOpsTeam
      register: privsub1Instance_out

    # ================= PRIVATE APP INSTANCE 2 =================

    - name: Create Private App Instance in privsub3
      amazon.aws.ec2_instance:
        name: DBInstance
        key_name: "{{ keyName }}"
        region: "{{ region }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        vpc_subnet_id: "{{ privsub3id }}"
        security_group: App-tier-sg
        network:
          assign_public_ip: false
        wait: yes
        tags:
          Tier: App
          Project: Vprofile
          Owner: DevOpsTeam
      register: privsub3Instance_out